services:
  - type: web
    name: transferbanc
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_USER
        value: appuser
      - key: DB_PASS
        value: appsecret
      - key: DB_NAME
        value: transferdb
      - key: DB_HOST
        fromDatabase:
          name: transferdb
          property: host
      - key: DB_PORT
        fromDatabase:
          name: transferdb
          property: port
      - key: DATABASE_URL
        fromDatabase:
          name: transferdb
          property: connectionString

databases:
  - name: transferdb
    plan: free
