services:
  - type: web
    name: transferbanc
    env: java
    plan: free
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/transferbanc-0.0.1-SNAPSHOT.jar
    envVars:
      - key: DB_USER
        value: appuser
      - key: DB_PASS
        value: appsecret
      - key: DB_NAME
        value: transferdb
      - key: DB_HOST
        fromDatabase:
          name: transferdb
          property: host
      - key: DB_PORT
        fromDatabase:
          name: transferdb
          property: port
      - key: JDBC_DATABASE_URL
        fromDatabase:
          name: transferdb
          property: connectionString
      - key: R2DBC_DATABASE_URL
        value: r2dbc:postgresql://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}
      - key: SPRING_FLYWAY_ENABLED
        value: "true"

databases:
  - name: transferdb
